README.md
code/app/build.gradle
code/app/src/main/java/com/adobe/marketing/mobile/consentTestApp/ConsentTestApplication.java
code/build.gradle
code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/ConsentConstants.java
code/gradle.properties

Update version and dependencies for v1.0.0 release

---

Makefile

Run 'lint' before assemble

---

.github/workflows/maven-release.yml

Use Java 8 as it is required by Gradle 6

---

.github/workflows/maven-snapshot.yml

Use Java 8 as it is required by Gradle 6.

---

.github/workflows/maven-release.yml

Use GPG_KEY_ID secret in script

---

code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/Consent.java

Minor doc updates

---

.github/workflows/maven-release.yml
.github/workflows/maven-snapshot.yml
code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/Consent.java

Dev -> Staging  v1.0.0 (GPG + Doc updates)

---

code/build.gradle
code/gradle.properties

Production Mobilecore depedency

---

.circleci/config.yml
codecov.yml

Upload coverage reports to CodeCov

---

code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/ConsentConstants.java
code/gradle.properties

Update version to v1.0.1

---

code/edgeconsent/build.gradle

Update docs link

---

.github/workflows/maven-release.yml
.github/workflows/maven-snapshot.yml
code/edgeconsent/build.gradle

Update github workflow to v1 branch for dev-v1 and update doc link

Update github workflow to v1 branch for dev-v1 and update doc link

---

CODE_OF_CONDUCT.md
COPYRIGHT
Documentation/README.md
Documentation/api-reference.md
Documentation/getting-started-test-app.md
Documentation/getting-started.md
LICENSE
README.md

- Doc updates for 2.0.0 registration instructions
- Use the standard format for main extension README
- Update to latest code of conduct, license year

Doc updates for 2.0.0 release and files cleanup and restructure 

---

Documentation/api-reference.md

Update registerExtension API doc link

Update registerExtension API doc link

---

Documentation/api-reference.md
Documentation/getting-started.md
code/gradle.properties

Add Kotlin syntax and samples in api-reference + Update core version

---

code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/Consents.java

Use DataReader for reading consent metadata

---

Documentation/api-reference.md

Remove Kotlin syntax in API doc

Remove Kotlin syntax in API doc

---

code/build.gradle
code/edgeconsent/build.gradle

Fix lint warning in gradle files.

Fix lint warning in gradle files

---

Documentation/api-reference.md
Documentation/getting-started.md

Remove unused file consumer-rules.pro
Remove deprecated registerExtension API
Update the extension versions to 3 in the getting-started doc

Remove unused file, registerExtension API and update the version to 3 in the getting-started

---

code/app/build.gradle.kts
code/build.gradle.kts
code/edgeconsent/build.gradle.kts
code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/ConsentConstants.java
code/gradle.properties

Update version to 3.0.0-beta.1

Update version to 3.0.0-beta.1

---

code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/ConsentConstants.java
code/edgeconsent/src/test/java/com/adobe/marketing/mobile/edge/consent/ConsentExtensionVersionTest.java

Update extension version to 3.0.0 to be consistent as the others extensions. 
Remove the version check test for gradle.properties and extension version, it will be covered in github action.

Update extension_version back to 3.0.0 for beta 1 release.

---

.circleci/config.yml
Documentation/getting-started.md
README.md
code/build.gradle.kts

Cleanup before the release
- Gettin started docs - Update Bom setup - groovy + kotlin instructions
- Update gradle lib to gp-3.0.0
- Remove sample app reference in the Readme
- Update Ci to run build sample only for staging and main

Cleanup before the release

---

code/app/build.gradle.kts
code/app/src/main/java/com/adobe/marketing/mobile/edge/consent/testapp/ConsentTestApplication.java

Remove Assurance extension, it is not being used in the test app.

Remove Assurance extension

---

Documentation/getting-started-test-app.md
README.md

Update getting-started-test-app.md to use correct applicationId

---

code/edgeconsent/src/main/AndroidManifest.xml
code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/ConsentConstants.java
code/gradle.properties

(EdgeConsent 3.0.1) Added support for the new MobileCore.initialize API introduced in Core

---

code/edgeconsent/src/main/AndroidManifest.xml
code/edgeconsent/src/main/java/com/adobe/marketing/mobile/edge/consent/ConsentConstants.java
code/gradle.properties

(EdgeConsent 3.0.1) Added support for the new MobileCore.initialize API introduced in Core (#103)
* Update AndroidManifest.xml to include extension information.
* Updating version to 3.0.1
* Update gradle.properties
---------

Downmerge main to dev to include 3.0.1 release changes

---

code/app/build.gradle.kts
code/app/src/main/AndroidManifest.xml
code/app/src/main/java/com/adobe/marketing/mobile/edge/consent/testapp/AssuranceActivity.java
code/app/src/main/java/com/adobe/marketing/mobile/edge/consent/testapp/ConsentTestApplication.java
code/app/src/main/java/com/adobe/marketing/mobile/edge/consent/testapp/MainActivity.java
code/app/src/main/java/com/adobe/marketing/mobile/edge/consent/testapp/TestingActivity.java
code/app/src/main/res/drawable/row_background.xml
code/app/src/main/res/layout/activity_assurance.xml
code/app/src/main/res/layout/activity_main.xml
code/app/src/main/res/layout/activity_testing.xml
code/app/src/main/res/layout/consent_preference_row.xml
code/app/src/main/res/menu/app_menu.xml
code/app/src/main/res/values/strings.xml

Add updates to `app` module:
- Add extensions Edge, Identity Edge, and Assurance
- Change UI to allow selecting different consent preferences. The update only allows setting a specific list of consents to either yes or no. This should be sufficient for most testing, though we can expand this in the future if needed.
- Add activity with test scenarios, such as repeatedly calling Consent.update()
- Add activity to connect to Assurance.
- use MobileCore.initialize()
- use BOM for dependencies
[Screen_recording_20250813_162834.webm](https://github.com/user-attachments/assets/8d4acbfc-3e61-4d15-9728-f2d2280a30ef)
[Screen_recording_20250813_162743.webm](https://github.com/user-attachments/assets/87f533a3-3949-468b-8bab-e93c9a6e7d20)

Updates to sample app
